version: '3.7'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb-phonebook
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: personal-db
    ports:
      - "27017:27017"
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-phonebook
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8085:8080"
    command: start-dev